import Groq from "groq-sdk";
import "dotenv/config";
import { getTopPlayersToolDef, getTopPlayers } from "./tools/getTopPlayers.js";
import type { GetTopPlayersArgs, GetTopPlayersResult, PlayerData } from "./tools/getTopPlayers.js";
import { renderChartToolDef, renderChart } from "./tools/renderChart.js";
import type { RenderChartArgs, RenderChartResult } from "./tools/renderChart.js";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

if (!process.env.GROQ_API_KEY) {
  throw new Error("[groqAgent] GROQ_API_KEY is not set. Copy .env.example to .env and fill it in.");
}

const MODEL = process.env.GROQ_MODEL || "llama-3.3-70b-versatile";

const TOOLS: Groq.Chat.ChatCompletionTool[] = [getTopPlayersToolDef, renderChartToolDef];

// Args come from JSON.parse of the model's tool call and are validated inside
// each tool, so the impl signature is intentionally loose.
type ToolResult = GetTopPlayersResult | RenderChartResult;
type ToolImpl = (args: unknown) => ToolResult | Promise<ToolResult>;

const TOOL_IMPLS: Record<string, ToolImpl> = {
  getTopPlayers: (args) => getTopPlayers(args as GetTopPlayersArgs),
  renderChart: (args) => renderChart(args as RenderChartArgs),
};

const SYSTEM_PROMPT = `You are a football (soccer) analytics assistant backed by real Understat data
stored in a database. You can call:
- getTopPlayers: fetches real ranked player stats. ALWAYS use this instead of
  guessing numbers when the user asks about stat leaders, rankings, or comparisons.
- renderChart: declares how to visualize the getTopPlayers result you just fetched.
  Call it right after getTopPlayers whenever a chart would help.

CRITICAL TOOL CALLING RULE: Always pass numeric parameters (like limit or min_minutes) as raw JSON numbers (e.g. 10), NEVER as strings (e.g. "10").

Never invent player names or stat values — only use numbers returned by getTopPlayers.
After tool results come back, write a short, natural-language summary (2-4 sentences)
highlighting the standout names/numbers. Keep it conversational, not a data dump —
the chart on screen will already show the full list.`;

export interface HistoryMessage {
  role: "user" | "assistant";
  content: string;
}

export interface AgentResult {
  text: string | null;
  chartSpec: RenderChartArgs | null;
  data: PlayerData | null;
}

/**
 * Runs the full 2-step tool-calling loop for one user message.
 * Returns { text, chartSpec, data } — text and chartSpec come from the model,
 * `data` is the raw, un-touched DB result used to actually draw the chart.
 */
export async function runAgent(userMessage: string, history: HistoryMessage[] = []): Promise<AgentResult> {
  const messages: Groq.Chat.ChatCompletionMessageParam[] = [
    { role: "system", content: SYSTEM_PROMPT },
    ...history,
    { role: "user", content: userMessage },
  ];

  // --- Step 1: ask the model what to do ---
  let first: Groq.Chat.ChatCompletion;
  try {
    first = await groq.chat.completions.create({
      model: MODEL,
      messages,
      tools: TOOLS,
      tool_choice: "auto",
      temperature: 0.3,
    });
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    if (errMsg.includes("tool call validation failed") || errMsg.includes("invalid_request_error")) {
      console.warn("[groqAgent] Tool call validation failed on initial attempt. Retrying with explicit directive...");
      first = await groq.chat.completions.create({
        model: MODEL,
        messages: [
          ...messages,
          {
            role: "system",
            content: "Remember: numeric parameters for tool calls MUST be raw JSON integers (e.g. limit: 10), NOT strings (e.g. limit: \"10\").",
          },
        ],
        tools: TOOLS,
        tool_choice: "auto",
        temperature: 0.1,
      });
    } else {
      throw err;
    }
  }

  const firstChoice = first.choices[0];
  if (!firstChoice) {
    throw new Error("Groq returned no choices.");
  }
  const firstMsg = firstChoice.message;
  const toolCalls = firstMsg.tool_calls || [];

  if (toolCalls.length === 0) {
    // Model answered directly without needing data (e.g. "hello", or a
    // general football question that doesn't need a DB lookup).
    return { text: firstMsg.content, chartSpec: null, data: null };
  }

  // --- Execute each requested tool for real ---
  messages.push(firstMsg as Groq.Chat.ChatCompletionAssistantMessageParam);

  let rawPlayerData: PlayerData | null = null; // the ground-truth data, never generated by the LLM
  let chartSpec: RenderChartArgs | null = null;

  for (const call of toolCalls) {
    const fnName = call.function.name;
    const args = JSON.parse(call.function.arguments || "{}");
    const impl = TOOL_IMPLS[fnName];

    let result: ToolResult;
    if (!impl) {
      result = { error: `Unknown tool ${fnName}` };
    } else {
      result = await impl(args);
    }

    if (fnName === "getTopPlayers" && "players" in result) {
      rawPlayerData = result;
    }
    if (fnName === "renderChart" && "chart_type" in result) {
      chartSpec = result;
    }

    const toolMsg: Groq.Chat.ChatCompletionToolMessageParam = {
      role: "tool",
      tool_call_id: call.id,
      content: JSON.stringify(result),
    };
    messages.push({ ...toolMsg, name: fnName } as Groq.Chat.ChatCompletionMessageParam);
  }

  // --- Step 2: ask the model to summarize the real tool results in words ---
  const second = await groq.chat.completions.create({
    model: MODEL,
    messages,
    temperature: 0.4,
  });

  const secondChoice = second.choices[0];
  const finalText = secondChoice ? secondChoice.message.content : null;

  return {
    text: finalText,
    chartSpec,
    data: rawPlayerData, // frontend renders the chart from THIS, not from finalText
  };
}
