import Groq from "groq-sdk";
import "dotenv/config";
import { getTopPlayersToolDef, getTopPlayers } from "./tools/getTopPlayers.js";
import type { GetTopPlayersArgs, GetTopPlayersResult, PlayerData } from "./tools/getTopPlayers.js";
import { renderChartToolDef, renderChart } from "./tools/renderChart.js";
import type { RenderChartArgs, RenderChartResult } from "./tools/renderChart.js";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

if (!process.env.GROQ_API_KEY) {
  throw new Error("[groqAgent] GROQ_API_KEY is not set. Copy .env.example to .env and fill it in.");
}

const MODEL = process.env.GROQ_MODEL || "openai/gpt-oss-120b";

const TOOLS: Groq.Chat.ChatCompletionTool[] = [getTopPlayersToolDef, renderChartToolDef];

// Args come from JSON.parse of the model's tool call and are validated inside
// each tool, so the impl signature is intentionally loose.
type ToolResult = GetTopPlayersResult | RenderChartResult;
type ToolImpl = (args: unknown) => ToolResult | Promise<ToolResult>;

const TOOL_IMPLS: Record<string, ToolImpl> = {
  getTopPlayers: (args) => getTopPlayers(args as GetTopPlayersArgs),
  renderChart: (args) => renderChart(args as RenderChartArgs),
};

const SYSTEM_PROMPT = `You are a football (soccer) analytics assistant backed by real Understat data
stored in a database. You can call:
- getTopPlayers: fetches real ranked player stats. ALWAYS use this instead of
  guessing numbers when the user asks about stat leaders, rankings, or comparisons.
- renderChart: declares how to visualize the getTopPlayers result.
  Always use x_key: "name", y_key: "value", and chart_type: "bar" (or "line"/"scatter").

CRITICAL TOOL CALLING RULES:
1. Always pass numeric parameters (like limit or min_minutes) as raw JSON numbers (e.g. 10), NEVER as strings (e.g. "10").
2. Never output raw XML, <function> tags, or raw JSON in your final text response.
3. After tool results come back, write a short, natural-language summary (2-4 sentences)
highlighting the standout names/numbers. Keep it conversational, not a data dump —
the chart on screen will automatically show the visual chart.`;

export interface HistoryMessage {
  role: "user" | "assistant";
  content: string;
}

export interface AgentResult {
  text: string | null;
  chartSpec: RenderChartArgs | null;
  data: PlayerData | null;
}

/**
 * Runs the full 2-step tool-calling loop for one user message.
 * Returns { text, chartSpec, data } — text and chartSpec come from the model,
 * `data` is the raw, un-touched DB result used to actually draw the chart.
 */
export async function runAgent(userMessage: string, history: HistoryMessage[] = []): Promise<AgentResult> {
  const messages: Groq.Chat.ChatCompletionMessageParam[] = [
    { role: "system", content: SYSTEM_PROMPT },
    ...history,
    { role: "user", content: userMessage },
  ];

  let rawPlayerData: PlayerData | null = null; // the ground-truth data, never generated by the LLM
  let chartSpec: RenderChartArgs | null = null;
  let finalText: string | null = null;

  const MAX_TURNS = 5;
  let turn = 0;

  while (turn < MAX_TURNS) {
    turn++;
    let response: Groq.Chat.ChatCompletion;

    try {
      response = await groq.chat.completions.create({
        model: MODEL,
        messages,
        tools: TOOLS,
        tool_choice: "auto",
        temperature: 0.3,
      });
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      if (errMsg.includes("tool call validation failed") || errMsg.includes("invalid_request_error")) {
        console.warn("[groqAgent] Tool call validation failed. Retrying with explicit directive...");
        response = await groq.chat.completions.create({
          model: MODEL,
          messages: [
            ...messages,
            {
              role: "system",
              content: "Remember: numeric parameters for tool calls MUST be raw JSON integers (e.g. limit: 10), NOT strings (e.g. limit: \"10\").",
            },
          ],
          tools: TOOLS,
          tool_choice: "auto",
          temperature: 0.1,
        });
      } else {
        throw err;
      }
    }

    const choice = response.choices[0];
    if (!choice) {
      throw new Error("Groq returned no choices.");
    }

    const msg = choice.message;
    const toolCalls = msg.tool_calls || [];

    if (toolCalls.length === 0) {
      // Model answered directly without needing further tools
      finalText = msg.content;
      break;
    }

    // Execute each requested tool for real
    messages.push(msg as Groq.Chat.ChatCompletionAssistantMessageParam);

    for (const call of toolCalls) {
      const fnName = call.function.name;
      let args: unknown = {};
      try {
        args = JSON.parse(call.function.arguments || "{}");
      } catch (e) {
        console.warn(`[groqAgent] Failed to parse tool arguments for ${fnName}:`, call.function.arguments);
      }

      const impl = TOOL_IMPLS[fnName];

      let result: ToolResult;
      if (!impl) {
        result = { error: `Unknown tool ${fnName}` };
      } else {
        result = await impl(args);
      }

      if (fnName === "getTopPlayers" && "players" in result) {
        rawPlayerData = result;
      }
      if (fnName === "renderChart" && "chart_type" in result) {
        chartSpec = result;
      }

      const toolMsg: Groq.Chat.ChatCompletionToolMessageParam = {
        role: "tool",
        tool_call_id: call.id,
        content: JSON.stringify(result),
      };
      messages.push({ ...toolMsg, name: fnName } as Groq.Chat.ChatCompletionMessageParam);
    }
  }

  // Fallback: If getTopPlayers fetched real DB data, ensure we always have a valid chartSpec
  if (rawPlayerData && !chartSpec) {
    chartSpec = {
      chart_type: "bar",
      title: `Top ${rawPlayerData.count} Players by ${rawPlayerData.stat}`,
      x_key: "name",
      y_key: "value",
    };
  }

  // Sanitize pseudo-XML <function=...> tags if the model outputs them into text
  if (finalText) {
    finalText = finalText.replace(/<function=\w+>.*?<\/function>/gs, "").trim();
  }

  if (!finalText || finalText.length === 0) {
    if (rawPlayerData) {
      finalText = `Here are the top ${rawPlayerData.count} players ranked by ${rawPlayerData.stat}.`;
    } else {
      finalText = "I ran into an issue generating a summary, but the request completed.";
    }
  }

  return {
    text: finalText,
    chartSpec,
    data: rawPlayerData, // frontend renders the chart from THIS, not from finalText
  };
}
